### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by AnionCation** [KaiserAndres/kaiserBot#1]
:JACZAC!~JACZAC@2601:647:4C01:E8B9:C8B:22D5:5BC1:1897 PRIVMSG #RPGSTUCK_JACZAC :DONT SPOIL HP ROLLS N SHIT

:JACZAC!~JACZAC@2601:647:4C01:E8B9:C8B:22D5:5BC1:1897 PRIVMSG #RPGSTUCK_JACZAC :!ROLL 1D20

Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\Tyche\bot.py", line 182, in <module>
    chann = (text.split(":")[1]).split(" ")[2]
IndexError: list index out of range

**Comment by KaiserAndres** [comment]
Reworked channel getting function. Solved.
